config/routes.rb
PerguntasUniversitarias::Application.routes.draw do
  
  root :to => 'home#index'
  get  'home/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              :controllers => { :omniauth_callbacks => "services", :registrations => "registrations"}

  devise_scope :user do
    match "services" => "services#index"
    match "services/index" => "services#index"
    resources :services, :only => [:index, :create, :destroy]
  end

  resources :notifications
  resources :questions do
    resources :comments
    resources :answers
  end 
  
  get 'tags/:tag', to: 'questions#index', as: :tag
  
  resources :profiles, :only => [:index, :show, :edit, :update]
  match '/users/:id', :to => 'users#show', :as => :user
  match '/:username', :to => 'profiles#show_by_username', :as => :profile
 

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :user_id
  belongs_to :profile
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy
  acts_as_taggable

  validates_uniqueness_of :title, :case_sensitive => false

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  # GET /questions
  # GET /questions.json
  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag])
    else
      @questions = Question.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    
    @comment = Comment.new
    @answer = Answer.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create

    @question = Question.new(params[:question])
    @question.user_id = current_user.profile.user_id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
	
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<%= div_for question do %>
  <h2><%= link_to_unless_current question.title, question %></h2>
  <%= simple_format question.body %>
  <em>added by <%= link_to question.user.username, question.user %></em>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.title %></td>
    <td><%= question.body %></td>
    <td>Tags: <%= raw question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><b>Title:</b>
  <%= @question.title %></h2>
</p>

<p>
  <b>Body:</b>
  <%= @question.body %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<h5>Question Comments</h5>

<div id="comments">
  <%= render @question.comments %>
</div>

<h6>New Comment</h6>

<%= render 'comments/form' %>

<h3>Answers</h3>

<div id="answers">
  <%= render @question.answers %>
</div>

<h4>New Answer</h4>

<%= render 'answers/form' %>