config/routes.rb
PerguntasUniversitarias::Application.routes.draw do
  
  root :to => 'home#index'
  get  'home/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              :controllers => { :omniauth_callbacks => "services", :registrations => "registrations"}

  devise_scope :user do
    match "services" => "services#index"
    match "services/index" => "services#index"
    resources :services, :only => [:index, :create, :destroy]
  end

  resources :notifications
  resources :questions do
    resources :comments
    resources :answers
  end 
  
  get 'tags/:tag', to: 'questions#index', as: :tag
  
  resources :profiles, :only => [:index, :show, :edit, :update]
  match '/users/:id', :to => 'users#show', :as => :user
  match '/:username', :to => 'profiles#show_by_username', :as => :profile
 

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_merit

  attr_accessible :name, :profile_image_url, :birthdate, :website, :user_id

  belongs_to :user

  validates_uniqueness_of :user_id
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  def show_by_username
    #@profile = Profile.joins(:user).where(:user => {:username => params[:username]})
    user = User.find_by_username(params[:username])

    @profile = Profile.find_by_user_id(user)
    respond_to do |format|
      format.html
      format.json { render json: @profile }
    end
  end

  def edit
    if not user_signed_in?
      flash[:error] = I18n.t('devise.failure.unauthenticated')
      redirect_to new_user_session_path
    elsif current_user.id.to_i != params[:id].to_i
      flash[:error] = "You can only edit your own profile."
      redirect_to "/"
    else
      @profile = Profile.find(params[:id])
    end
  end

  def update
    if not user_signed_in?
      flash[:error] = I18n.t('devise.failure.unauthenticated')
      redirect_to new_user_session_path
    elsif current_user.id.to_i != params[:id].to_i
      flash[:error] = I18n.t('devise.failure.unauthenticated')
      redirect_to new_user_session_path
    else
      @profile = Profile.find(params[:id])

      respond_to do |format|
        if @profile.update_attributes(params[:profile])
          format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name, :autofocus => true %></div>

  <div><%= f.label :profile_image_url %><br />
  <%= f.url_field :profile_image_url %></div>

  <div><%= f.label :birthdate %><br />
  <%= f.date_select :birthdate, 
    {:start_year => Time.now.year,
     :end_year => 1900,
     :order => [:day, :month, :year],
     :prompt => {:month => 'Month', :day => 'Day', :year => 'Year'}}
   %>

  <div><%= f.label :website %><br />
  <%= f.url_field :website %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>profile image url</th>
    <th>birthdate</th>
    <th>website</th>
    <th>user_id</th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.id %></td>
    <td><%= profile.name %></td>
    <td><%= profile.profile_image_url %></td>
    <td><%= profile.birthdate %></td>
    <td><%= profile.website %></td>
    <td><%= profile.user_id %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
  </tr>
<% end %>
</table>

app/views/profiles/show.html.erb
ID: <%= @profile.id %>
Name: <%= @profile.name %>
Profile Image URL: <%= @profile.profile_image_url %>
Birthdate: <%= @profile.birthdate %>
Website: <%= @profile.website %>
User_ID: <%= @profile.user_id %>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/show_by_username.html.erb
ID: <%= @profile.id %>
Name: <%= @profile.name %>
Profile Image URL: <%= @profile.profile_image_url %>
Birthdate: <%= @profile.birthdate %>
Website: <%= @profile.website %>
User_ID: <%= @profile.user_id %>
<br>
Badges String: <%= @profile.badges %>
<br>
Reputation: <%= @profile.points %>
<br>
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>