config/routes.rb
PerguntasUniversitarias::Application.routes.draw do
  
  root :to => 'home#index'
  get  'home/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              :controllers => { :omniauth_callbacks => "services", :registrations => "registrations"}

  devise_scope :user do
    match "services" => "services#index"
    match "services/index" => "services#index"
    resources :services, :only => [:index, :create, :destroy]
  end

  resources :notifications
  resources :questions do
    resources :comments
    resources :answers
  end 
  
  get 'tags/:tag', to: 'questions#index', as: :tag
  
  resources :profiles, :only => [:index, :show, :edit, :update]
  match '/users/:id', :to => 'users#show', :as => :user
  match '/:username', :to => 'profiles#show_by_username', :as => :profile
 

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body
  belongs_to :user
  belongs_to :question
  has_many :comments, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :load_question

  # GET /comments/1/edit
  def edit
    @answer = current_user.answers.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @answer = @question.answers.build(params[:answer])
    @answer.user = current_user
    
    if @answer.save
      redirect_to @question, notice: "Answer was created."
    else
      render :new
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @answer = current_user.answers.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to @question, notice: "Answer was updated."
    else
      render :edit
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @answer = current_user.answers.find(params[:id])
    @answer.destroy

    redirect_to @question, notice: "Answer was destroyed."
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%= div_for answer do %>
  <p><strong><%= link_to answer.user.profile.name, answer.user %> says</strong></p>
  <%= simple_format answer.body %>
  <% if answer.user == current_user %>
    <p>
      <%= link_to 'Edit',  edit_question_answer_path(@question, answer) %> |
      <%= link_to "Delete", [@question, answer], method: :delete %>
    </p>
  <% end %>
<% end %>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, rows: 8, cols: 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>