config/routes.rb
PerguntasUniversitarias::Application.routes.draw do
  
  root :to => 'home#index'
  get  'home/index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              :controllers => { :omniauth_callbacks => "services", :registrations => "registrations"}

  devise_scope :user do
    match "services" => "services#index"
    match "services/index" => "services#index"
    resources :services, :only => [:index, :create, :destroy]
  end

  resources :notifications
  resources :questions do
    resources :comments
    resources :answers
  end 
  
  get 'tags/:tag', to: 'questions#index', as: :tag
  
  resources :profiles, :only => [:index, :show, :edit, :update]
  match '/users/:id', :to => 'users#show', :as => :user
  match '/:username', :to => 'profiles#show_by_username', :as => :profile
 

  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Perguntas Universitárias</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<header>
  <div class="navbar navbar-static-top">
    <div class="navbar-inner">
          <%= link_to "Perguntas Universitárias", root_path, :class => 'brand' %>

          <ul class="nav pull-right">
            <li>
              <form class="navbar-search">
                <input type="text" class="search-query" placeholder="Pesquisar">
              </form>
            </li>
            <li class="divider-vertical"></li>
            <li><a href="/users/login" class="pull-right">Login</a></li>
            <li class="divider-vertical"></li>
            <li><a href="/users/sign_up" class="pull-right">Registrar-se</a></li>
          </ul>
    </div>
  </div>
</header>

  <% if current_user %>
    <%= link_to 'Edit account', edit_user_registration_path %> |
    <%= link_to 'Edit profile', edit_profile_path(current_user) %> |
    <%= link_to 'Edit login services', services_index_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <br>
    Logged in as <strong><%= current_user.profile ? current_user.profile.name : current_user.username %></strong>. 
  <% end %>

  <%= render 'layouts/messages' %>
  <%= yield %>

</body>
</html>